version: '3'

services:
   fslc-discord:
      restart: "always" 
      build:
         dockerfile: ./Dockerfile.dev
      env_file:
         - .env
      ports:
         - "5001:5001"
      volumes:
         - "./gunicorn.conf.py:/etc/gunicorn.conf.py"
         - "./fslc_discord/:/fslc_discord/fslc_discord"
         - "./export:/fslc_discord/export"
