version: '3'

services:
   fslc-discord:
      restart: "always" 
      build:
         dockerfile: ./Dockerfile
      env_file:
         - .env
      ports:
         - "5001:5001"
      volumes:
         - "./gunicorn.conf.py:/etc/gunicorn.conf.py"
         - "./db.sqlite:/fslc_discord/db.sqlite"
